on:
  workflow-dispatch:
  push:
    branches: [ "Look-for-advanced-installer" ]
jobs:
  runs-on: ubuntu-latest
  steps:
  - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.6.x - 3.11.x'
