
name: test_windows_dockerfile

on:
  workflow_dispatch:

jobs:




  build_and_test:
    name: "Build and test ssh-server in Windows Docker container, using Python script."
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    # - uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.10' 
    # - run: >
    #     pip install
    #     paramiko
    #     docker
    #     dockerfile-generator
        
    # - name: "Cache the Docker image"
    #   uses: ScribeMD/docker-cache@0.3.7
    #   with:
    #     key: docker-${{ runner.os }}-${{ hashFiles('./Dockerfile') }}
        
    - name: "Build the Windows Dockerfile from the command line" 
      run: docker build -t test_pyclisson_ssh_windows_nano_server .

    # - name: "Run Hello World via paramiko, saving to .json, Python script"
    #   run: python test_windows_dockerfile.py
      
    # - name: upload special chars files
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: special_chars
    #     path: "*.json"
